// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Ensure a string is provided to satisfy TypeScript.
    // Use the environment variable if present, otherwise fall back to the local sqlite file.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
